import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'knowledge' }],
  slangSidebar: [{ type: 'autogenerated', dirName: 'slang' }],
};

export default sidebars;
