import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'knowledge' }],
  terminologySidebar: [{ type: 'autogenerated', dirName: 'termins' }],
};

export default sidebars;
